db: Use tags instead of magic to hide internal jobs
sifive/wake pull request #1576
Opened 2024-05-28 22:49 UTC by V-FEXrt

Manually and directly tag jobs as hidden then filter those jobs out from inspection instead of relying on magic character in the jobs commandline/label

2024-05-28 23:00 UTC, ag-eitilt requested changes
Much better than the old hack!  I do think this as it is will probably start showing `<write>`, `<mkdir>`, `<source>`, and `<claim>` jobs (caught by the previous line 160, but not decorated with the new tag yet).  I'd argue that showing `<write>` and `<mkdir>` jobs is a good thing so I'm fine with those two (though open to discussion if either of you feel otherwise), but we should probably still hide `<source>` and `<claim>`.

2024-05-29 16:33 UTC, V-FEXrt commented
Went ahead and hid all those jobs along with the http jobs (I still consider it an implementation detail that http requests are jobs)

We can discuss `<write>`/`<mkdir>` here or separately. I don't have a strong opinion in the matter but the fact that they are mostly noise and somewhat trivially inspectable leads me to lean towards leaving them out.

aside: we could/should probably add an `--internal` flag that only matches internal jobs

2024-05-29 16:35 UTC, ag-eitilt approved these changes

2024-05-29 16:35 UTC, ag-eitilt commented on share/wake/lib/system/job.wake
> +    | setJobTag "inspect.visibility" "hidden"
Good call.

2024-05-29 16:35 UTC, ag-eitilt commented on share/wake/lib/system/io.wake
I'd like to talk about these two in the meeting before merging the PR.

2024-05-29 18:14 UTC, ag-eitilt commented on share/wake/lib/system/io.wake
Demonstrated in the meeting: The filter is only applied to `--last`/`--last-used` and `--last-executed`, so any other DB queries will still display the hidden jobs; this fine-grained control was my ideal solution (but I wasn't sure it was possible), so I'm quite happy with the current state.

2024-05-30 04:27 UTC, colinschmidt approved these changes
LGTM

2024-05-30 19:54 UTC, merged